# Generated by Django 3.1.7 on 2021-04-13 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_shouldieat'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouldieat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
