# Generated by Django 3.1.7 on 2021-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=(1.80)),
            preserve_default=False,
        ),
    ]
