# Generated by Django 3.1.7 on 2021-04-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_profile_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
    ]
