# Generated by Django 3.1.7 on 2021-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_remove_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=1.8),
            preserve_default=False,
        ),
    ]
