# Generated by Django 3.1.7 on 2021-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.URLField(default='capstone/images/profile.png'),
        ),
    ]
