# Generated by Django 3.1.7 on 2021-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_auto_20210428_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
