# Generated by Django 3.1.7 on 2021-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_auto_20210428_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.URLField(default='https://icons-for-free.com/iconfiles/png/512/free+outline+people+profile+ui+icon-1320196081912311498.png', max_length=300),
        ),
    ]
